### ISSUE TITLE
Solved: Not visible in WebUI NZBGET on Qnap

### ISSUE THREAD

**Issue by JohnHalfords** [caronc/nzbget-subliminal#10]
Hello,

Solved Issue: (anyway, solved for me, thought you migth want to know)

Change line 23 and 282 from
### NZBGET POST-PROCESSING SCRIPT                                          ###

Then the script will be detected and visible in the WebUI from NZBGET 12 on Qnap, only then the setting can be made through WebUI.

John Halfords, The Netherlands

**Comment by caronc** [comment]
i didn't see this ticket and pushed what should have referred to ticket #12 in that last commit.

Unfortunately NZBGet 15 is due to come out soon, v14 is incredibly stable and v13 is too.  I sort of broke support for v12.  But i'm glad you found a working solution.
