### ISSUE TITLE
language code in subtitle filename

### ISSUE THREAD

**Issue by dlmarston** [caronc/nzbget-subliminal#13]
hi caron,

this is only an aesthetics issue, but can you add the country code letters - e.g. "en" for english to the filename?

my media player, plex picks up on this info and displays it. without it, it only shows "unknown" next to the subtitle.

cheers,

dave

**Comment by caronc** [comment]
Hmm, this is 'single mode'.  Just turn this off (if using NZBGet) otherwise refrain from specifying the __--single__ (__-s__) switch on the command line.

I believe this will give you your expected results where:
_your.show.mkv_ fetches you _your.show.en.srt_
