### ISSUE TITLE
Question/Feature Request: SRT files only

### ISSUE THREAD

**Issue by f3bruary** [caronc/nzbget-subliminal#16]
I'm gonna switch from filebot to subliminal today and was wondering if subliminal could force .srt files only like filebot can ? I don't want any other formats like sub/idx/ssa/etc.

In filebot I can do --output srt to only have it download srt files. Is there such a thing in subliminal ? Or does it do this by default already ?

**Comment by caronc** [comment]
You're good; if Filebot does the other types then it's got the upper hand on me here.  (nzbget-)subliminal script ONLY deals with .srt files.

**Comment by f3bruary** [comment]
Alright, thanks for the quick response.
