### ISSUE TITLE
Detect already present 3-letter language codes.

### ISSUE THREAD

**Issue by f3bruary** [caronc/nzbget-subliminal#17]
I've been using Filebot and switched to Subliminal to see if it works better for me. Currently my entire library is thus mostly 3-letter country coded subs like *.eng.srt, *.dut.srt, *.fre.srt.

I just ran Subliminal and (withouth -o) it's searching for subs even though I already have them in that certain language.

Can you make it detect 3-letter country codes too, so it can skip searching for that language ?

**Comment by caronc** [comment]
Do you just want it to pick up on this type for preliminary scanning (when deciding whether to do a fetch)? Or should it also download the content and save them in the 3 letter extension too for consistency?

It will be really easy for me to just look at the first 2 characters (__fr__ = **fr**e, __en__ = **en**g) and ignore the third letter.  The latter is a bit more involved; but still doable.

**Comment by caronc** [comment]
Check out the master branch if you have time, It'll handle the part I mentioned was easy above. It should at least allow you to scan your entire library and not force the fetching of all your subtitles again.

**Comment by f3bruary** [comment]
I just want it to detect existing subtitles, regardless of whether it's a 2 or 3 letter language code. I ran the script yesterday and it fetched .nl.srt while .dut.srt was already there for example. Same for .en.srt/.eng.srt etc.

I might be easy to just look at the first 2 characters, but in some cases it won't match. .nl.srt vs. .dut.srt for example. Sure there's .nld.srt but that's a different "ISO 639-2 T" while .dut.srt is "ISO 639-2 B" and the latter is what Plex uses for 3 char langs.

**Comment by caronc** [comment]
Thank you for that info! You greatly helped my coding direction in solving the problem.  I think i got it (check the master branch).

There is enough smarts not to handle all languages and their converted Terminology (T) and Bibliographic (B) reference identifiers.  This knowledge also allowed me to also enhance the language handling further by accepting the following as input and processing it all the same way:

* --lang **nl**
* --lang **Dutch**
* --lang **dut**
* --lang **nld**

Combinations (even mix matched) work now too:
*  --lang **Dutch**,**en**,**fra**

More importantly (and specific to your issue), I check for all of the language references (except the full name such as Dutch, English, etc) for subs that may already exist.

Let me know how it goes!

**Comment by caronc** [comment]
Note to self, the following rolls back a git commit and also destroys all comments made here on it.
```bash
git push -f origin HEAD^:master
```

I realize you already closed this ticket; but everything got lost/reset somehow on github after my actions. For some reason it rolled back time to the point where this ticket is back to being open.  I'm closing it now.  Thanks for your help!
