### ISSUE TITLE
SyntaxError: invalid syntax, line 389

### ISSUE THREAD

**Issue by f3bruary** [caronc/nzbget-subliminal#18]
SyntaxError: invalid syntax
  File "Subliminal/Subliminal.py", line 389
    DEFAULT_VIDEO_PERMISSIONS = 0o644

Getting this suddenly. Should it be 0644 perhaps ? I'll try and close if it works like that.

**Comment by f3bruary** [comment]
Never mind. There was something wrong with my $PATH.

**Comment by caronc** [comment]
Thank you, and good find. I'm going to have to look back into what commit had an 'o' get placed there. Pushed to the master.  I'll dig back to the commit that broke this in case something else got stuck in there.  Glad everything is otherwise working now for you.
