### ISSUE TITLE
Loading configuration failed when copying nzbget-subliminal to scripts directory

### ISSUE THREAD

**Issue by amaumene** [caronc/nzbget-subliminal#22]
Hi,

I'm using Fedora 23 and when I'm copying the nzbget-subliminal directory to the scripts directory of nzbget (version 16.4) and then click on settings I have this error message:

    Loading configuration failed
    Could not load template configuration file nzbget.conf. The file contains descriptions of options and is needed to display settings page. The file comes with NZBGet distribution archive and is usually automaically installed into the right location. This seems not to be a case with your installation though.
    
    Please edit your configuration file (/usr/share/httpd/.nzbget) in a text editor and set the option ConfigTemplate to point to the template configuration file nzbget.conf.

I have no idea how to fix this and there is nothing in the logs. When I'm removing nzbget-subliminal from the scripts directory everything is working again and I can access the settings menu.

Any idea on how to debug that ?

Thanks in advance.

Regards,

**Comment by amaumene** [comment]
For some reason it works when disabling selinux.

**Comment by caronc** [comment]
I got a second email from another post you made about it being SELinux causing your issue (the post is gone now). Did you end up solving the problem? Or is it still occurring?
Does this occur if you use other scripts too? Or just this one?

What RPM package are you using to install NZBGet or are you manually compiling and installing it?

**Comment by amaumene** [comment]
Hi,
My bad, I thought disabling SELinux fixed the issue but I was wrong. I built nzbget manually. I'm using videosort which work great. I'm sorry but I haven't more information to help you.

**Comment by caronc** [comment]
One thing you could try doing if you're interested in using the script is put it back how you had it (in the scripts dir of NZBGet). Then open a shell and manually execute Subliminal.py. I'm curious as to if it's a dependency issue or if you're getting an error with the script itself. It could also be a permission issue. What user does NZBGet run as for you?

**Comment by caronc** [comment]
Were you ever able to figure this out? Did you still need help?

**Comment by caronc** [comment]
I'm going to close this case since I haven't heard back in a while. Please feel free to comment or jump back in at anytime you wish to reinvestigate the issue if it's still occurring.
