### ISSUE TITLE
Fails to include dist-info data files of subliminal after compiling . 

### ISSUE THREAD

**Issue by nateshmbhat** [caronc/nzbget-subliminal#33]
Hello caronc thanks so much for your work . **Help wanted here : -** 

I am trying to convert a small python code which uses the download_best_subtitle function to an executable using pyinstaller . But sadly its not working right . I am sure that i must have not included all the files or may not have included the right modules in the spec file .  I think the error occurs because , somehow the program is not able to see the `subliminal-2.0.5.dist-info`  which contains the entry point data to be accessed by the compiled exe . here is the spec file code which i am using ......Can't seem to make it work . :(

```
# -*- mode: python -*-

block_cipher = None
options = [('v',None,'OPTION')]

a = Analysis(['subtiler_getter.py'],
             pathex=['C:\\Users\\Natesh\\Desktop\\subtitle trying','C:\Program Files\Python35\Lib\site-packages'],
             binaries=[],
             datas=[('guessit/tlds', 'guessit/tlds'), ('babelfish/data', 'babelfish/data'),('subliminal-2.0.5.dist-info/*','data')],
             hiddenimports=['subliminal-2.0.5.dist-info','dogpile.cache.backends.file','dogpile.cache','subliminal','babelfish','stevedore','appdirs'],
             hookspath=['.'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
a.data+=[("subliminal-2.0.5.dist-info","subliminal-2.0.5.dist-info")]
			 
			 
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='Subtitler',
          debug=True,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='Subtitler')

```

**Can you _please_ give me the exact command or the spec file** for pyinstaller which is needed to convert this into a working compiled executable ? . I would be really very grateful.  @caronc .

Here is the simple code which i am trying for three days to convert to exe . ( novice here :) )  : - 
```

import subliminal
import sys,os,requests
import argparse;
import logging;
from babelfish import Language

# configure the cache

subliminal.region.configure('dogpile.cache.dbm', arguments={'filename': 'cachefile.dbm'})



Path = input("Enter the path for the video :- ") ;

if os.path.isfile(args.Path):
	videos = [subliminal.scan_video(args.Path)];
else:
	videos = subliminal.scan_videos(args.Path) ;

subs = subliminal.download_best_subtitles(videos,{Language('eng')} ) ;
print(list(subs.values()))
for v in videos:
	subliminal.save_subtitles(v, subs[v]) ;

```

**Comment by caronc** [comment]
I'm not sure how much help I'm going to be.  This isn't Subliminal; this is just a wrapper to it (kind of like your doing).  The other thing is my version of Subliminal is based on the v1.7 branch.  Things differ from v1.7 and v2.0 quite a bit.  So referencing how it's done in this script might not work out the best in the end for you.

[Here is how](https://github.com/Diaoul/subliminal/blob/605a761bf913393a855f6d2af278e9537fcb120b/subliminal/cli.py#L296-L458) it's done just using the Subliminal CLI code right from the actual source.
