### ISSUE TITLE
Default category

### ISSUE THREAD

**Issue by WoLpH** [caronc/nzbget-subliminal#5]
Just installed the subliminal script and I noticed that the default TV category for the post-processing mode is "tv, tv2". While nzbget defaults to "Series", might be better to include that as well :)

**Comment by caronc** [comment]
Thanks for bringing this to my attention; I'll bundle it into a regular release soon enough and make it available via rpms on [my site](http://nuxref.com/repo) and through the [nzbget plugin thread](http://nzbget.net/forum/viewtopic.php?f=8&t=1422&sid=9a827b1607052c6d00936bf798211fbc) eventually.
