### ISSUE TITLE
Changing the amount of on-screen logging

### ISSUE THREAD

**Issue by dlmarston** [caronc/nzbget-subliminal#6]
hi there, great app. have moved across to it from the original subliminal script.

i'm wondering if there is any way to control the amount of onscreen logging?

what i'd like to do is exclude the "Skipping - Subtitle(s) already exist for" reports, so that i only see those which have had subtitles downloaded, or are missing.

is this functionality available, or would it need to be coded in?

cheers,

dave

**Comment by caronc** [comment]
Shouldn't be a problem at all (it is a code change, but a very easy one). What I'll do is continue to display the skip message(s), but only do so if your running the script in --debug (-D) mode.

Would that work for you?

**Comment by dlmarston** [comment]
that would be awesome, thanks.

i have a few other ideas for your consideration (with no expectation that you implement them). let me know if you want me to post them, and if so as one issue or separate issues.

**Comment by caronc** [comment]
Feel free to do so! Just as a heads up though, I really only poke at this code during the weekends (it's more of a side hobby). So I apologize in advance if you need to wait til Sunday-ish.

**Comment by dlmarston** [comment]
i completely understand about the side hobby approach. So no need to apologise :)
